apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-helloworld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-helloworld
  template:
    metadata:
      labels:
        app: golang-helloworld
    spec:
      containers:
        - name: golang-helloworld
          image: quay.io/jfronius/golang-helloworld:2026-09-22
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: pv-data
              mountPath: /pv-data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: golang-helloworld-pvc
