apiVersion: v1
kind: Secret
metadata:
  name: app-secret1
type: Opaque
stringData:
  DB_PASSWORD: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret2
type: Opaque
stringData:
  DB_PASSWORD: changeme
