apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan3440
  annotations:
    field.cattle.io/description: Creates VLAN3440 network attachment definition
    #  key: string
   labels:
     {}
    #  key: string
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan3440","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":3440,"ipam":{}}
    __clone: true
